data_pipeline_name: &MODULENAME "longitudinal_data"
description: "bringing data into the events table"
longitudinal_table_name: "longitudinal_data"
longitudinal_database: "dbx_accelerator_gold"
dimenstion_tables:
  - input_table_schema: "dbx_accelerator_gold"
    input_table_name: "encounters"
    columns_list: {"patientID":"patient_id", "timestamp":"encounter_dt", "measureID":"encounter_id", "measureName":"doctor_name", "measureResult":"note"}
    event_type: "Encounter and Notes"
    table_needs_join: "false"
    current_tbl_join_key: ""
    join_tbl_name: ""
    join_tbl_database: ""
    join_tbl_join_key: ""
    columns_need_retrieve: []
  - input_table_schema: "dbx_accelerator_gold"
    input_table_name: "diagnoses"
    columns_list: {"patientID":"patient_id", "timestamp":"diagnosis_dt", "measureID":"diagnosis_id", "measureName":"diagnosis_name", "measureResult":""}
    event_type: "Diagnoses"
    table_needs_join: "true"
    current_tbl_join_key: "encounter_id"
    join_tbl_name: "encounters"
    join_tbl_database: "dbx_accelerator_gold"
    join_tbl_join_key: "encounter_id"
    columns_need_retrieve: [ "patient_id"]
  - input_table_schema: "dbx_accelerator_gold"
    input_table_name: "medications"
    columns_list: {"patientID":"patient_id", "timestamp":"encounter_dt", "measureID":"medication_id", "measureName":"medication_name", "measureResult":"dosage"}
    event_type: "Medications"
    table_needs_join: "true"
    current_tbl_join_key: "encounter_id"
    join_tbl_name: "encounters"
    join_tbl_database: "dbx_accelerator_gold"
    join_tbl_join_key: "encounter_id"
    columns_need_retrieve: ["patient_id", "encounter_dt"]
  - input_table_schema: "dbx_accelerator_gold"
    input_table_name: "symptoms"
    columns_list: {"patientID":"patient_id", "timestamp":"onset_dt", "measureID":"symptom_id", "measureName":"symptom_name", "measureResult":""}
    event_type: "Symptoms"
    table_needs_join: "true"
    current_tbl_join_key: "encounter_id"
    join_tbl_name: "encounters"
    join_tbl_database: "dbx_accelerator_gold"
    join_tbl_join_key: "encounter_id"
    columns_need_retrieve: ["patient_id"]
  - input_table_schema: "dbx_accelerator_gold"
    input_table_name: "labs"
    columns_list: {"patientID":"patient_id", "timestamp":"lab_dt", "measureID":"lab_id", "measureName":"lab_name", "measureResult":"lab_result"}
    event_type: "Labs"
    table_needs_join: "true"
    current_tbl_join_key: "encounter_id"
    join_tbl_name: "encounters"
    join_tbl_database: "dbx_accelerator_gold"
    join_tbl_join_key: "encounter_id"
    columns_need_retrieve: ["patient_id"]
  - input_table_schema: "dbx_accelerator_gold"
    input_table_name: "procedures"
    columns_list: {"patientID":"patient_id", "timestamp":"procedure_dt", "measureID":"procedure_id", "measureName":"procedure_name", "measureResult":""}
    event_type: "Procedures"
    table_needs_join: "true"
    current_tbl_join_key: "encounter_id"
    join_tbl_name: "encounters"
    join_tbl_database: "dbx_accelerator_gold"
    join_tbl_join_key: "encounter_id"
    columns_need_retrieve: ["patient_id"]
  - input_table_schema: "dbx_accelerator_gold"
    input_table_name: "patient_history"
    columns_list: {"patientID":"patient_id", "timestamp":"", "measureID":"history_id", "measureName":"medical_history", "measureResult":"surgical_history"}
    event_type: "Patient History"
    table_needs_join: "false"
    current_tbl_join_key: ""
    join_tbl_name: ""
    join_tbl_database: ""
    join_tbl_join_key: ""
    columns_need_retrieve: []
  - input_table_schema: "dbx_accelerator_gold"
    input_table_name: "biosamples"
    columns_list: {"patientID":"patient_id", "timestamp":"collection_dt", "measureID":"sample_id", "measureName":"sample_type", "measureResult":"result"}
    event_type: "Biosamples"
    table_needs_join: "false"
    current_tbl_join_key: ""
    join_tbl_name: ""
    join_tbl_database: ""
    join_tbl_join_key: ""
    columns_need_retrieve: []
