data_pipeline_name: &MODULENAME "dbxa-labs-source-to-gold"
description: "CSV config for DBX accelerator DLT workflow"
repo_root: "" #fill in later
bronze_database: &DBBRONZE "dbx_accelerator_bronze"
silver_database: &DBSILVER  "dbx_accelerator_silver"
gold_database: &DBGOLD "dbx_accelerator_gold"
bronze_ingestion_details:
  source_file_path: "s3://dbx-accelerator/data/medical_data_landing/labs/"
  source_file_format: "csv"
  source_file_first_row_is_header: "True" #for csv
  source_file_delimiter: "," # for csv
  source_file_schema_path: "" # tbd
  source_file_multiline: "" #for json
  source_file_name_pattern: "" #tbd
  bronze_schema: *DBBRONZE
  bronze_table: &TABLENAME "labs"
  load_type: "incremental_append_only" # full/upsert/incremental_append_only/delete_and_append
  partition_key: []
  delete_match_on_key: "" # needed only for load type delete_and_append
  Upsert_match_on_keys: [""] # needed only for load type upsert
  explode_on_key: "" # needed only for any json array
  archived_processed_file_path: 
  archived_rejected_file_path:
  archived_rejected_record_path:
  file_validation_rules: ["record count"] # file validation rules, record count check
consent_process_details: 
  #These are the fields for each individual table
  consent_curtbl_needscheck: "False" #If the table does not need to be consent checked, then set it to "False"
  consent_curtbl_col_date: "details_collected_dt" #If table needs join, this can be left blank
  consent_tbl_date_col: [""] #date columns in users table to be used for consent check
  consent_tbl_id_col: "id"
  consent_curtbl_col_participant_id: "patient_id" #This is the column that contains unique participant,
  consent_curtbl_col_join: "patient_id" #column in dependent table which will join with users table
  consent_curtbl _col_needsrenamed: “” #use case: app_analytics where column needs to be renamed." If false leave value below blank
  consent_curtbl_col_renamed: ""
  consent_curtbl_needsjoin: "" #If false, leave values below blank 
  consent_jointbl: “" #If a record table doesn’t have a date column, it must be joined to another table which does have a date
  consent_jointbl_col: "" #join ‘column in parent table that will join with users table   
  consent_curtbl_child_join_col: [""] #child table join columns 
  consent_reference_database: *DBGOLD
  consent_reference_table: "consent_details"
  quarantine_records: ""
silver_ingestion_details:
  #to be filled when more info available
  source_bronze_schema: *DBBRONZE
  source_bronze_table: *TABLENAME
  silver_schema: *DBSILVER
  silver_table: *TABLENAME
  quarantine_schema: "data_platform_audit"
  quarantine_table: "quarantine_records"
  merge_key: ""
  data_check:
    expectations:
      - data_validation_check: "check_value_empty" 
        relevant_columns: ["lab_id", "lab_name"]
silver_to_gold_details:
  #to be filled when more info available
  silver_schema: *DBSILVER
  silver_table: *TABLENAME
  gold_schema: *DBGOLD
  gold_table:  *TABLENAME
  merge_id: "lab_id"
  logical_order: "silver_last_modified_dt"
  transform_functions: [""] # list of functions to use
  date col: ""
  cutoff date: "" # Cut-off date for First snapshot as requested by Study team
  participant_col: ""
  included_participants_table: "" # Table with first 50 subjects enrolled as requested by Study team