data_pipeline_name: &MODULENAME "dicom"
description: "Moving dicom files across medallion layer"
repo_root: 
bronze_database: &DBBRONZE "dbx_accelerator_bronze"
silver_database: &DBSILVER  "dbx_accelerator_silver"
gold_database: &DBGOLD "dbx_accelerator_gold"
ingestion_details: 
  source_file_path: "/FileStore/dicom"
  source_file_format: "dcm" 
  source_file_first_row_is_header: "" #for csv
  source_file_delimiter: "," #for csv
  source_file_schema_path: "" #tbd
  source_file_multiline: "" #for json
  source_file_name_pattern: "" #tbd
  destination_table: "patient_dicom_image_details" #fill in later 
  load_type: "incremental_append_only" # full/upsert/incremental_append_only/delete_and_append
  partition_key: []
  delete_match_on_key: "" # needed only for load type delete_and_append
  upsert_match_on_keys: [""] # needed only for load type upsert
  explode_on_key: "" # needed only for any json array
  archived_processed_file_path: 
  archived_rejected_file_path:
  archived_rejected_record_path:
  file_validation_rules: [""] # file validation rules, record count check