data_pipeline_name: &MODULENAME "longitudinal_data"
description: "template config for longitudinal data model"
longitudinal_table_name: "longitudinal_data" # Name of table to store the longitudinal data model
longitudinal_database: "" # Name of database to store the longitudinal data model
dimenstion_tables:
  - input_table_schema: "database1" # Name of database the table is in
    input_table_name: "table1" # The name of the table
    columns_list: {"patientID":"", "timestamp":"", "measureID":"", "measureName":"", "measureResult":""} # the mapping of the source columns to the longitudinal data model columns
    event_type: "" # The name of the event type
    table_needs_join: "false" # Whether the table needs a join to write into the longitudinal data model
    current_tbl_join_key: "" # The join key for the table
    join_tbl_database: "" # The name of the database with the table to join with
    join_tbl_name: "" # The name of the table to join with
    join_tbl_join_key: "" # The join key for the table to join with
    columns_need_retrieve: [] # The columns that needs to be retreived ("")
  - input_table_schema: "database1" # Name of database the table is in
    input_table_name: "table2" # The name of the table
    columns_list: {"patientID":"", "timestamp":"", "measureID":"", "measureName":"", "measureResult":""} # the mapping of the source columns to the longitudinal data model columns
    event_type: "" # The name of the event type
    table_needs_join: "false" # Whether the table needs a join to write into the longitudinal data model
    current_tbl_join_key: "" # The join key for the table
    join_tbl_database: "" # The name of the database with the table to join with
    join_tbl_name: "" # The name of the table to join with
    join_tbl_join_key: "" # The join key for the table to join with
    columns_need_retrieve: [] # The columns that needs to be retreived ("")

